### ISSUE TITLE
v0.88B wont work

### ISSUE THREAD

**Issue by Leproide** [jilleb/mqb-pm#101]
Hi,
the previous version work like a charm (only one little bug on gps cause crash) but the new v0.88B not show any value on screen.
How i can fix?
Composition media 0876

**Comment by jilleb** [comment]
Make sure no battery saving is applied to the vex vag service and the app itself.

**Comment by Pantelleria79** [comment]
Hello I wanted to know if app performance monitor only works with mib2. I have a troc 2021 mib3 and the app dials do not move let me know if there will be any updates to make them read by mib3.
Thank you

**Comment by jilleb** [comment]
It will not work on mib3 unless you grab engine data by Torque
