### ISSUE TITLE
Informazioni app performance monitor

### ISSUE THREAD

**Issue by Pantelleria79** [jilleb/mqb-pm#105]
Buongiorno volevo sapere se app performance monitor funziona solo con mib2. Io ho una troc 2021 mib3 e i quadranti dell'app non si muovono fatemi sapere se ci sarà qualche aggiornamento per fare si che vengono letti da mib3.
Grazie

**Comment by jilleb** [comment]
Please speak english

**Comment by Pantelleria79** [comment]
Hello I wanted to know if app performance monitor only works with mib2. I have a troc 2021 mib3 and the app dials do not move let me know if there will be any updates to make them read by mib3.
Thank you

**Comment by Pantelleria79** [comment]
Hello I wanted to know if app performance monitor only works with mib2. I have a troc 2021 mib3 and the app dials do not move let me know if there will be any updates to make them read by mib3.
Thank you
