### ISSUE TITLE
No data from Seat Ateca 

### ISSUE THREAD

**Issue by k4rm3l0** [jilleb/mqb-pm#114]
Hello,
I installed Performance Monitor and Martoreto's extension. I tried several indicators but seems the app is not able to retrieve any data from the car.

I have a Seat Ateca 2021. 

![Screenshot_20210523-100103](https://user-images.githubusercontent.com/4647229/119252710-f2ab9700-bbad-11eb-8b08-cb51f9c13a6f.jpg)

![Screenshot_20210523-100339](https://user-images.githubusercontent.com/4647229/119252761-30102480-bbae-11eb-9834-485e6d60087c.jpg)

Can you help me? Thanks.

**Comment by jilleb** [comment]
This specific infotainment system does not have any Exlap communication channel.
