### ISSUE TITLE
Turbo Pressure don't move

### ISSUE THREAD

**Issue by gennematte** [jilleb/mqb-pm#120]
Hi,
PM work correctly and read all data I have on display except of turbo pressure that stay on 0 (tried absolute and relative), what to do for it? (Attached car sw info)
![20210614_184437_HDR](https://user-images.githubusercontent.com/85826788/122539380-d291bb00-d027-11eb-8adc-236499fd329b.jpg)

**Comment by jilleb** [comment]
This is a case of your engine not supplying this information to your infotainment system. It's common on most cars, except for the sporty ones.

**Comment by gennematte** [comment]
Taking the data with torque could be a solution?

**Comment by jilleb** [comment]
Yes, getting data with torque seems to go wrong lately.
