### ISSUE TITLE
New android auto version performance monitor

### ISSUE THREAD

**Issue by Michelemk8** [jilleb/mqb-pm#122]
hi, i wanted to know if you are working to make sure that the performance monitor app can be used with the latest versions of android auto. It doesn't show it to me in sync.

**Comment by jilleb** [comment]
Did you read the readme? 
This app, and any custom Android Auto app, will not show up in your Android Auto unless you have a way to circumvent the lockout of 3rd party apps that Google applied after people started building YouTube clients for AA...


So please, check the readme while I close this comment 😏
