### ISSUE TITLE
Latest release 042B timer crashes

### ISSUE THREAD

**Issue by kaisertgc** [jilleb/mqb-pm#13]
Hi, all data showing working fine but when i click timer it turns back to clocks screen. Any solutions for this? Thanks.

**Comment by petous22** [comment]
I have same problem with timer.

**Comment by jilleb** [comment]
It's in fact a bigger issue, that causes the app to crash when selecting Stopwatch and Graphs. Logcats don't teach me anything... 

Merging it with issue #15 , closing this one.
