### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Merkta** [jilleb/mqb-pm#141]
| :exclamation:  Issues that aren't in English will  be closed and igored.  |
|-----------------------------------------|

**Describe the bug**
Be as descriptive as possible, and write in English.
Make sure you've read the Readme and searched for similar issues before asking a question.
Issues not in English or without any detail will not be closed and ignored. 
Be kind and respectful and maybe most importantly: Don't be lazy (just posting a duplicate error like "it's crashing" or "it doesn't get data") while you're expecting me to do all the work for free 😄

**To Reproduce**
Including a logcat or Debug log is very helpful. Use Google to find out how to get those on your specific phone/Android version.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by killme12993** [comment]
> ❗ Issues that aren't in English will be closed and igored.
> **Describe the bug** A clear and concise description of what the bug is. Be as descriptive as possible, and write in English. Make sure you've read the Readme and searched for similar issues before asking a question. Issues not in English or without any detail will not be closed and ignored. Be kind and respectful and maybe most importantly: Don't be lazy (just posting a duplicate error like "it's crashing" or "it doesn't get data") while you're expecting me to do all the work for free 😄
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
>    Including a logcat or Debug log is very helpful. Use Google to find out how to get those on your specific phone/Android version.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.
