### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by javigody** [jilleb/mqb-pm#17]
Hello, I translated your application into Spanish. Here is the string file. Thanks for the app, is awesome!
[values-es.zip](https://github.com/jilleb/mqb-pm/files/1856464/values-es.zip)

**Comment by jilleb** [comment]
That is great, thank you so much! I will include it.

Op wo 28 mrt. 2018 16:51 schreef javigody <notifications@github.com>:

**Comment by jilleb** [comment]
Included in 302c0399a8b3036d8c0a670b57498e4557cc11de 👍 Thanks @javigody
