### ISSUE TITLE
Several modifications in order to be fully translatable.

### ISSUE THREAD

**Issue by javigody** [jilleb/mqb-pm#19]
Hello, I have modificated several files to make the app fully translatable. All the strings files has been modified and only it's needs to translate the new entries.  I hope you find this files useful. I have also change compile by implementation in build.gradle. Only the modified files are in the zip. Thanks!
[mqb-pm.zip](https://github.com/jilleb/mqb-pm/files/1864162/mqb-pm.zip)

**Comment by jilleb** [comment]
Thank you! :-) I will merge your code soon.

**Comment by jilleb** [comment]
Implemented with commit cd9d718e4ef99ec2fce8bafd67a59c22f714591e
Thanks a lot for contributing!! 👍
