### ISSUE TITLE
LICENSE.md missing

### ISSUE THREAD

**Issue by basisbit** [jilleb/mqb-pm#3]
could you please add a license file, thus clearly showing if you would allow for other developers to contribute to this project? Thanks a lot in advance! (maybe MIT license would be really nice for a project like this)

**Comment by jilleb** [comment]
Good point 👍 
Will add it.

**Comment by jilleb** [comment]
Added [in latest commit](https://github.com/jilleb/mqb-pm/commit/20994e72234bc7b43d25ad534cf324d3c48f7c57
)
