### ISSUE TITLE
Could the scale (max value) to be able to be customized (can be modified by user)?

### ISSUE THREAD

**Issue by davidchen1976** [jilleb/mqb-pm#33]
As title. 
For ex:
The Power (kW) max scale value is 300.
Can I change it to 150 to fit my vehicle (mine is a Skoda Kodiaq 2.0 TSI / 132kw)?

**Comment by davidchen1976** [comment]
Thanks, BTW, if possible could you please add "Turbo Pressure %" as well? It's quite useful to monitor VAG vehicles. :+1:

**Comment by davidchen1976** [comment]
Found there are 2 turbo related items under "Torque Scan":
Turbo Boost & Vacuum Gague [ff1202]
Turbo Pressure Control [70]
Many thanks! :+1:

**Comment by jilleb** [comment]
> Found there are 2 turbo related items under "Torque Scan":
> Turbo Boost & Vacuum Gague [ff1202]
> Turbo Pressure Control [70]
> Many thanks! 👍

Both of these are included :-)
