### ISSUE TITLE
Location info from Google maps if exlap location info isnt available.

### ISSUE THREAD

**Issue by jilleb** [jilleb/mqb-pm#35]
Currently, there is no location for people without exlap data. Make a fallback to Google maps location.

**Comment by mobrembski** [comment]
I've created something simmilar:
https://github.com/jilleb/mqb-pm/pull/56
It uses basic android geocoding from location API to solve street name/street number/city

**Comment by jilleb** [comment]
Ahhh nice :-)
The same feature was implemented by @Lucas-M-G the other day , I'll have a look to see I can merge your code in a safe way

**Comment by mobrembski** [comment]
Ahh, right, i haven't noticed that you merged Lucas-M-G changes :(
I will take a look at it, but as i can see he added an display of navigation instructions, i think this might be a different feature.
Hold on, i will try to rebase my patches.

**Comment by Lucas-M-G** [comment]
My changes only display the title of the Google Maps notification. If there is no active navigation, the current Street was displayed otherwise the next instruction. This solution doesn’t need any extra requests, but it is not the cleanest solution.

**Comment by jilleb** [comment]
Closing issue, I believe it's done :-)
