### ISSUE TITLE
UpdateClock - optimalization

### ISSUE THREAD

**Issue by divacky** [jilleb/mqb-pm#39]
I use this optimization in the updateclock method. On older mobile phones is faster to see the current value.
![updateclock](https://user-images.githubusercontent.com/37082286/51441699-4b17b480-1cd4-11e9-8a90-562c695e00ad.JPG)

**Comment by jilleb** [comment]
Allright, I will look into this :-)

**Comment by jilleb** [comment]
Implemented with 2b442b28d8b1595d0893accf87e955fbbf4b5338
