### ISSUE TITLE
Info about "Black screen of death"

### ISSUE THREAD

**Issue by nerone-github** [jilleb/mqb-pm#4]
Hey, since i have been working on AA apps as well i have some information you may find useful. The black screen happens mostly with Huawei and Honor devices due to an implementation error on their ROM. The quickest solution to fix this it to clear the Android Auto apk cache. This will make OEM apps work again ;)

https://github.com/nerone-github/LocalSpeedcam/issues/1  

This happens when the error occurrs

**Comment by jilleb** [comment]
:-) thanks, that's useful information!

**Comment by jilleb** [comment]
Updated readme in commit 6e8f4eff828616c1bd1e710f00d4485daa391893
