### ISSUE TITLE
Add multiple-panel layout

### ISSUE THREAD

**Issue by xDefcon** [jilleb/mqb-pm#45]
Hello, 
I want to suggest the option to have multiple panels, as the current interface can contain a maximum of 3 graphical "indicators"  (with relative graphs by clicking on them) and four text-based views.

The multi-pane would be perfect if with a swipe to the left you could change the current pane with another one and have, for instance, twice as the information you want without configuring it in the app and having to disconnect/reconnect the phone.

I don't exclude the fact that I would be able in the future to open a pull request with the specified changes, I have to see the code of the Android Auto app.

**Comment by xDefcon** [comment]
Similar to #41

**Comment by divacky** [comment]
I made multiple layouts, but I am not allowed access to the new pullrequest. You can allow this?

**Comment by xDefcon** [comment]
@divacky in the meantime, could you upload your commits to the repository you forked? Thanks.

**Comment by jilleb** [comment]
> Can I grant access or should I do otherwise?

I checked the setetings, and everyone should be able to post a pull request.. strange stuff..

**Comment by divacky** [comment]
Sorry, I'm busy working. I am sending the changed files in the attachment. Can you compare files with the current version? Thank you
[mqb.zip](https://github.com/jilleb/mqb-pm/files/3574986/mqb.zip)

**Comment by divacky** [comment]
New pull request with multidashboard

**Comment by jilleb** [comment]
Niiiiice @divacky .I'll merge them tomorrow. Thanks!

**Comment by jilleb** [comment]
Merged, and it's very very cool :-)

**Comment by xDefcon** [comment]
> Merged, and it's very very cool :-)

Plan to add a new release with that changes?

**Comment by jilleb** [comment]
of course :-)
