### ISSUE TITLE
Forward data to exlap/canbus for displaying in Cluster

### ISSUE THREAD

**Issue by jilleb** [jilleb/mqb-pm#48]
@divacky, I've been looking in this for a long time, maybe you can assist..
Currently we are reading out data on the exlap channel, but we can also post data to it. I wonder if it's possible to get data back into the car, for instance for displaying in the cluster, like Polar FIS does:

They have hardware added onto the gatway that puts data to the canbus, as music-title/artist data, so it is displayed on the cluster:

![image](https://user-images.githubusercontent.com/8352494/59758193-a783fd80-928d-11e9-9f1b-b9459024e883.png)
![image](https://user-images.githubusercontent.com/8352494/59758266-d13d2480-928d-11e9-98dc-c45100770ccb.png)

**Comment by divacky** [comment]
POLAR FIS and similar devices do not send any data to the system just displaying audio information. The name of the song displays the values from the connected connector to the MQB socket. It's HW. I have tried different options and can eg control the radio or search for songs. Next, I tried to connect with a web service that would allow more.

**Comment by jilleb** [comment]
I believe they modify the music-information on the canbus and insert their own data instead which is then interpreted by the Cluster.

**Comment by jilleb** [comment]
With the  following code, we should be able to put data to the exlap channel:

```
CarVendorExtensionManagerLoader vexLoader =
        (CarVendorExtensionManagerLoader)mCar.getCarManager(
                CarVendorExtensionManagerLoader.VENDOR_EXTENSION_LOADER_SERVICE);
mVexManager = vexLoader.getManager(getVendorChannelName());
if (mVexManager == null) {
    throw new RuntimeException("Vendor channel not available");
}
mVexManager.registerListener(new CarVendorExtensionManager.CarVendorExtensionListener() {
    @Override
    public void onData(CarVendorExtensionManager carVendorExtensionManager, byte[] bytes) {
        // Do something with data
    }
});
mVexManager.sendData(new byte[] { (byte) 1, (byte) 2, (byte) 3 });
```

**Comment by jilleb** [comment]
Almost there, but that's for a different repository ;-)
