### ISSUE TITLE
[BUG] Clock doesn't respect car/phone format

### ISSUE THREAD

**Issue by mobrembski** [jilleb/mqb-pm#51]
Hi all,

I wanted just to flag, that Performance Monitor always uses 12 hour clock on title bar, no matter what clock type is set on phone or car.
Well, i know that maybe most of users use mqb-pm in USA, but remember of European fans :)

**Comment by jilleb** [comment]
haha whoops.. I'm not from the US, but I haven't noticed this while testing... going to fix it :-)

**Comment by mobrembski** [comment]
Pull request created :)

https://github.com/jilleb/mqb-pm/pull/52

**Comment by jilleb** [comment]
Merged, testing.

**Comment by jilleb** [comment]
Works!!
