### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by kaisertgc** [jilleb/mqb-pm#7]
Hi,
VW 0842 Passat Variant 2017 the model. App crashes after first plugin, if I unplug and plug again it doesnt. It is like unstable at this moment. I am using your latest release. I havent tried old releases. Hope you fix it sometime, nice app appreciate your work thanks.

**Comment by jilleb** [comment]
Thanks for testing and posting an issue :-)
Currently, I'm a bit occupied with family business, but I'll get back to the app when I can. 
What phone are you using? I've heard there are bad Android-Auto experiences for Huawei phones.

**Comment by kaisertgc** [comment]
Its Samsung Note8 7.1.1 android version. I will try to post a video show you whats happening. I tried all the versions of app but no success so far.

**Comment by kaisertgc** [comment]
I followed the instructions on readme. I cleared AA cache, reinstall Vag extensions and the app, still no success. Crashing.

**Comment by Lucas-M-G** [comment]
Sorry, wrong Issue-ID
