### ISSUE TITLE
Enginer Power Unit Selection

### ISSUE THREAD

**Issue by davidmh78** [jilleb/mqb-pm#77]
Hi, Skoda Octavia RS petrol engine, power appears in KW, ¿will it be possible to convert it to HP (1 KW = 1,34102 HP)? Maybe include it as a unit selection like pressure or temperature.

**Comment by adrienturpin974** [comment]
Plutôt 1,35962
Mais complètement d'accord avec vous ce serait un plus

**Comment by jilleb** [comment]
@adrienturpin974 , english please.


Next version will have seperate clocks for each unit. This way people can decide if they want a clock to be unit X or Y, and even have a KW and HP clock next to each other.
