### ISSUE TITLE
App just shows MPG gauge on AA

### ISSUE THREAD

**Issue by jaredneedell** [jilleb/mqb-pm#8]
I tried setting various gauges but whenever I open AA, it just shows MPG.

**Comment by jilleb** [comment]
What firmware and car model do you have? Not all all data elements are used by each car. Have a look in the ./CarLogs folder on your phone and tell me what data elements are in the logging.

**Comment by jaredneedell** [comment]
I have an RCD330 which was on the list, driving a MK5 Jetta. I have the latest software as of yesterday.

**Comment by jilleb** [comment]
It could be that the car isn't sharing any more data.
I'm currently in the process of adding ways to get non-exlap data to display as well. Let's hope this will work :-)

**Comment by jilleb** [comment]
@jaredneedell , does it work with the latest version?
