### ISSUE TITLE
No icon on android auto when connected to the car

### ISSUE THREAD

**Issue by bsiilvia** [jilleb/mqb-pm#80]
Hi @jilleb ,
I'm trying to connect Performance Monitor with my VW Polo 2018. I have a Xiaomi Mi A3.
I downloaded vag apk and performance monitor apk and then installed them and give them all the permissions.
My phone isn't rooted, is that a need?
Because, on my phone, the app seems to work correctly but in my car, when I connect my phone I don't see the icon of the performance monitor app.
Thank you to all who helps me.

**Comment by mzakharo** [comment]
You need to root and use another app to whitelist performance monitor with android auto
