### ISSUE TITLE
App crashing on start

### ISSUE THREAD

**Issue by gbruno89** [jilleb/mqb-pm#97]
App crashing when open in Android auto.
I have tried with debug and without but it doesn’t work.
I have lineage os 17.1 in Samsung galaxy a5 2016.
What to do?

**Comment by Leproide** [comment]
Try deny gps permission, for me work

**Comment by gbruno89** [comment]
Thank you Leproide, i'll try this trick. i have sent you message in vwgolfcommunity can you answer it?

**Comment by Leproide** [comment]
Credo di averti già risposto ieri sera sul tardi, controlla

**Comment by gbruno89** [comment]
Mi hai risposto ora alle 21. Ti ho risposto ora sulla chat

**Comment by jilleb** [comment]
Please only use English here.
